export const actions = {
    SET_LOCATION: 'SET_LOCATION',
    SET_ACTUAL_LOCATION: 'SET_ACTUAL_LOCATION',

    RESULTS_FETCH_REQUEST: 'RESULTS_FETCH_REQUEST',
    RESULTS_FETCH_SUCCESS: 'RESULTS_FETCH_SUCCESS',
    RESULTS_FETCH_FAILURE: 'RESULTS_FETCH_FAILURE',

    RESET_STATE: 'RESET_STATE',
    SET_ZOOM: 'SET_ZOOM',
}